### ISSUE TITLE
Not Working On Home Assistant 2022.7

### ISSUE THREAD

**Issue by Andrewpaps** [iamBiB/lovelace-htc-flipclock-weather#26]
Showing as following:

![image](https://user-images.githubusercontent.com/71562383/178221630-0795cbee-2234-4de8-b220-bc2fc4810b03.png)

**Comment by MajaGithuab** [comment]
Same here, any solution ?

**Comment by ibBogdan** [comment]
can you post your config and the issues listed in browser config.

**Comment by Buffer2000** [comment]
<img width="468" alt="image" src="https://github.com/iamBiB/lovelace-htc-flipclock-weather/assets/39482213/b95b7ac6-fb95-45df-b627-2927c273636d">

I got the same problem (may be) as above.

It seem that they cannot find all .png files. But as checking, the file exist.


[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (background.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (night.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (41-2.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (41-1.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (0-1.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (0-2.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (0-3.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (41-3.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (4.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (1.png, line 0)
[Error] Unhandled Promise Rejection: TypeError: e.indexOf is not a function. (In 'e.indexOf(".")', 'e.indexOf' is undefined)
	(anonymous function) (app-WGjVk0xiOKY.js:2:142593)
[Error] Unhandled Promise Rejection: TypeError: e.indexOf is not a function. (In 'e.indexOf(".")', 'e.indexOf' is undefined)
	performUpdate (app-WGjVk0xiOKY.js:2:143140)
	(anonymous function) (app-WGjVk0xiOKY.js:2:142653)
[Error] Unhandled Promise Rejection: TypeError: e.indexOf is not a function. (In 'e.indexOf(".")', 'e.indexOf' is undefined)
	(anonymous function) (app-WGjVk0xiOKY.js:2:142593)
[Error] Unhandled Promise Rejection: TypeError: e.indexOf is not a function. (In 'e.indexOf(".")', 'e.indexOf' is undefined)
	performUpdate (app-WGjVk0xiOKY.js:2:143140)
	(anonymous function) (app-WGjVk0xiOKY.js:2:142653)
[Error] Unhandled Promise Rejection: TypeError: e.indexOf is not a function. (In 'e.indexOf(".")', 'e.indexOf' is undefined)
	(anonymous function) (app-WGjVk0xiOKY.js:2:142593)


Also capture the log picture to show the path.

<img width="1021" alt="image" src="https://github.com/iamBiB/lovelace-htc-flipclock-weather/assets/39482213/63dd8ce1-a209-455e-8662-232bd142e264">

**Comment by Buffer2000** [comment]
[Solved - Only for me] I found that I named the folder wrong from custom_ui to custom-ui.

Thank you for your great work.
