### ISSUE TITLE
Not autoscaling

### ISSUE THREAD

**Issue by Crazy38TR** [iamBiB/lovelace-htc-flipclock-weather#28]
Hello, you know about the subject. But if a solution has been found, we ask for your help.

![not-scale](https://user-images.githubusercontent.com/57983995/212696237-9dcc3840-21a3-452f-bc4d-b96b9b68da8f.png)

**Comment by curtisdr** [comment]
I wonder if it's the size of your display.  The clock looks correct on my 10" Amazon Fire tablet.  Pretty sure it's 1080p.

**Comment by iamBiB** [comment]
#11
