### ISSUE TITLE
Windows size out of range...

### ISSUE THREAD

**Issue by BSD31** [iamBiB/lovelace-htc-flipclock-weather#34]
![Screenshot_20240124-005055~2.png](https://github.com/iamBiB/lovelace-htc-flipclock-weather/assets/11723095/7cb4376b-a54b-4311-9659-578a0eca791b)

Windows size out of range in my Sony Xperia XZ2.
Is there a simple resizing option ?
Thanks a lot for this excellent job.
Can we hope to find it one day on HACS ?

**Comment by appsfinder2** [comment]
me too 
Is there a simple resizing option ?
Thanks a lot for this excellent job.

**Comment by iamBiB** [comment]
#11
